/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package org.adtech.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

import java.io.Serial;

@org.apache.avro.specific.AvroGenerated
public class AdImpression extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  @Serial
  private static final long serialVersionUID = -2165687196898519356L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AdImpression\",\"namespace\":\"org.adtech.avro\",\"fields\":[{\"name\":\"event_id\",\"type\":\"string\"},{\"name\":\"event_type\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"user_id\",\"type\":\"string\"},{\"name\":\"publisher_name\",\"type\":\"string\"},{\"name\":\"advertiser_name\",\"type\":\"string\"},{\"name\":\"campaign_id\",\"type\":\"string\"},{\"name\":\"bid_price\",\"type\":\"double\"},{\"name\":\"device_type\",\"type\":\"string\"},{\"name\":\"ip_address\",\"type\":\"string\"},{\"name\":\"country_code\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"session_id\",\"type\":\"string\"},{\"name\":\"ad_position\",\"type\":\"string\"},{\"name\":\"is_skippable\",\"type\":\"boolean\"},{\"name\":\"time_watched_seconds\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AdImpression> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AdImpression> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AdImpression> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AdImpression> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AdImpression> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AdImpression to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AdImpression from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AdImpression instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AdImpression fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence event_id;
  private java.lang.CharSequence event_type;
  private long timestamp;
  private java.lang.CharSequence user_id;
  private java.lang.CharSequence publisher_name;
  private java.lang.CharSequence advertiser_name;
  private java.lang.CharSequence campaign_id;
  private double bid_price;
  private java.lang.CharSequence device_type;
  private java.lang.CharSequence ip_address;
  private java.lang.CharSequence country_code;
  private java.lang.CharSequence city;
  private java.lang.CharSequence session_id;
  private java.lang.CharSequence ad_position;
  private boolean is_skippable;
  private int time_watched_seconds;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AdImpression() {}

  /**
   * All-args constructor.
   * @param event_id The new value for event_id
   * @param event_type The new value for event_type
   * @param timestamp The new value for timestamp
   * @param user_id The new value for user_id
   * @param publisher_name The new value for publisher_name
   * @param advertiser_name The new value for advertiser_name
   * @param campaign_id The new value for campaign_id
   * @param bid_price The new value for bid_price
   * @param device_type The new value for device_type
   * @param ip_address The new value for ip_address
   * @param country_code The new value for country_code
   * @param city The new value for city
   * @param session_id The new value for session_id
   * @param ad_position The new value for ad_position
   * @param is_skippable The new value for is_skippable
   * @param time_watched_seconds The new value for time_watched_seconds
   */
  public AdImpression(java.lang.CharSequence event_id, java.lang.CharSequence event_type, java.lang.Long timestamp, java.lang.CharSequence user_id, java.lang.CharSequence publisher_name, java.lang.CharSequence advertiser_name, java.lang.CharSequence campaign_id, java.lang.Double bid_price, java.lang.CharSequence device_type, java.lang.CharSequence ip_address, java.lang.CharSequence country_code, java.lang.CharSequence city, java.lang.CharSequence session_id, java.lang.CharSequence ad_position, java.lang.Boolean is_skippable, java.lang.Integer time_watched_seconds) {
    this.event_id = event_id;
    this.event_type = event_type;
    this.timestamp = timestamp;
    this.user_id = user_id;
    this.publisher_name = publisher_name;
    this.advertiser_name = advertiser_name;
    this.campaign_id = campaign_id;
    this.bid_price = bid_price;
    this.device_type = device_type;
    this.ip_address = ip_address;
    this.country_code = country_code;
    this.city = city;
    this.session_id = session_id;
    this.ad_position = ad_position;
    this.is_skippable = is_skippable;
    this.time_watched_seconds = time_watched_seconds;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return event_id;
    case 1: return event_type;
    case 2: return timestamp;
    case 3: return user_id;
    case 4: return publisher_name;
    case 5: return advertiser_name;
    case 6: return campaign_id;
    case 7: return bid_price;
    case 8: return device_type;
    case 9: return ip_address;
    case 10: return country_code;
    case 11: return city;
    case 12: return session_id;
    case 13: return ad_position;
    case 14: return is_skippable;
    case 15: return time_watched_seconds;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: event_id = (java.lang.CharSequence)value$; break;
    case 1: event_type = (java.lang.CharSequence)value$; break;
    case 2: timestamp = (java.lang.Long)value$; break;
    case 3: user_id = (java.lang.CharSequence)value$; break;
    case 4: publisher_name = (java.lang.CharSequence)value$; break;
    case 5: advertiser_name = (java.lang.CharSequence)value$; break;
    case 6: campaign_id = (java.lang.CharSequence)value$; break;
    case 7: bid_price = (java.lang.Double)value$; break;
    case 8: device_type = (java.lang.CharSequence)value$; break;
    case 9: ip_address = (java.lang.CharSequence)value$; break;
    case 10: country_code = (java.lang.CharSequence)value$; break;
    case 11: city = (java.lang.CharSequence)value$; break;
    case 12: session_id = (java.lang.CharSequence)value$; break;
    case 13: ad_position = (java.lang.CharSequence)value$; break;
    case 14: is_skippable = (java.lang.Boolean)value$; break;
    case 15: time_watched_seconds = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'event_id' field.
   * @return The value of the 'event_id' field.
   */
  public java.lang.CharSequence getEventId() {
    return event_id;
  }


  /**
   * Sets the value of the 'event_id' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.event_id = value;
  }

  /**
   * Gets the value of the 'event_type' field.
   * @return The value of the 'event_type' field.
   */
  public java.lang.CharSequence getEventType() {
    return event_type;
  }


  /**
   * Sets the value of the 'event_type' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.CharSequence value) {
    this.event_type = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public java.lang.CharSequence getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'publisher_name' field.
   * @return The value of the 'publisher_name' field.
   */
  public java.lang.CharSequence getPublisherName() {
    return publisher_name;
  }


  /**
   * Sets the value of the 'publisher_name' field.
   * @param value the value to set.
   */
  public void setPublisherName(java.lang.CharSequence value) {
    this.publisher_name = value;
  }

  /**
   * Gets the value of the 'advertiser_name' field.
   * @return The value of the 'advertiser_name' field.
   */
  public java.lang.CharSequence getAdvertiserName() {
    return advertiser_name;
  }


  /**
   * Sets the value of the 'advertiser_name' field.
   * @param value the value to set.
   */
  public void setAdvertiserName(java.lang.CharSequence value) {
    this.advertiser_name = value;
  }

  /**
   * Gets the value of the 'campaign_id' field.
   * @return The value of the 'campaign_id' field.
   */
  public java.lang.CharSequence getCampaignId() {
    return campaign_id;
  }


  /**
   * Sets the value of the 'campaign_id' field.
   * @param value the value to set.
   */
  public void setCampaignId(java.lang.CharSequence value) {
    this.campaign_id = value;
  }

  /**
   * Gets the value of the 'bid_price' field.
   * @return The value of the 'bid_price' field.
   */
  public double getBidPrice() {
    return bid_price;
  }


  /**
   * Sets the value of the 'bid_price' field.
   * @param value the value to set.
   */
  public void setBidPrice(double value) {
    this.bid_price = value;
  }

  /**
   * Gets the value of the 'device_type' field.
   * @return The value of the 'device_type' field.
   */
  public java.lang.CharSequence getDeviceType() {
    return device_type;
  }


  /**
   * Sets the value of the 'device_type' field.
   * @param value the value to set.
   */
  public void setDeviceType(java.lang.CharSequence value) {
    this.device_type = value;
  }

  /**
   * Gets the value of the 'ip_address' field.
   * @return The value of the 'ip_address' field.
   */
  public java.lang.CharSequence getIpAddress() {
    return ip_address;
  }


  /**
   * Sets the value of the 'ip_address' field.
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.CharSequence value) {
    this.ip_address = value;
  }

  /**
   * Gets the value of the 'country_code' field.
   * @return The value of the 'country_code' field.
   */
  public java.lang.CharSequence getCountryCode() {
    return country_code;
  }


  /**
   * Sets the value of the 'country_code' field.
   * @param value the value to set.
   */
  public void setCountryCode(java.lang.CharSequence value) {
    this.country_code = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'session_id' field.
   * @return The value of the 'session_id' field.
   */
  public java.lang.CharSequence getSessionId() {
    return session_id;
  }


  /**
   * Sets the value of the 'session_id' field.
   * @param value the value to set.
   */
  public void setSessionId(java.lang.CharSequence value) {
    this.session_id = value;
  }

  /**
   * Gets the value of the 'ad_position' field.
   * @return The value of the 'ad_position' field.
   */
  public java.lang.CharSequence getAdPosition() {
    return ad_position;
  }


  /**
   * Sets the value of the 'ad_position' field.
   * @param value the value to set.
   */
  public void setAdPosition(java.lang.CharSequence value) {
    this.ad_position = value;
  }

  /**
   * Gets the value of the 'is_skippable' field.
   * @return The value of the 'is_skippable' field.
   */
  public boolean getIsSkippable() {
    return is_skippable;
  }


  /**
   * Sets the value of the 'is_skippable' field.
   * @param value the value to set.
   */
  public void setIsSkippable(boolean value) {
    this.is_skippable = value;
  }

  /**
   * Gets the value of the 'time_watched_seconds' field.
   * @return The value of the 'time_watched_seconds' field.
   */
  public int getTimeWatchedSeconds() {
    return time_watched_seconds;
  }


  /**
   * Sets the value of the 'time_watched_seconds' field.
   * @param value the value to set.
   */
  public void setTimeWatchedSeconds(int value) {
    this.time_watched_seconds = value;
  }

  /**
   * Creates a new AdImpression RecordBuilder.
   * @return A new AdImpression RecordBuilder
   */
  public static org.adtech.avro.AdImpression.Builder newBuilder() {
    return new org.adtech.avro.AdImpression.Builder();
  }

  /**
   * Creates a new AdImpression RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AdImpression RecordBuilder
   */
  public static org.adtech.avro.AdImpression.Builder newBuilder(org.adtech.avro.AdImpression.Builder other) {
    if (other == null) {
      return new org.adtech.avro.AdImpression.Builder();
    } else {
      return new org.adtech.avro.AdImpression.Builder(other);
    }
  }

  /**
   * Creates a new AdImpression RecordBuilder by copying an existing AdImpression instance.
   * @param other The existing instance to copy.
   * @return A new AdImpression RecordBuilder
   */
  public static org.adtech.avro.AdImpression.Builder newBuilder(org.adtech.avro.AdImpression other) {
    if (other == null) {
      return new org.adtech.avro.AdImpression.Builder();
    } else {
      return new org.adtech.avro.AdImpression.Builder(other);
    }
  }

  /**
   * RecordBuilder for AdImpression instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AdImpression>
    implements org.apache.avro.data.RecordBuilder<AdImpression> {

    private java.lang.CharSequence event_id;
    private java.lang.CharSequence event_type;
    private long timestamp;
    private java.lang.CharSequence user_id;
    private java.lang.CharSequence publisher_name;
    private java.lang.CharSequence advertiser_name;
    private java.lang.CharSequence campaign_id;
    private double bid_price;
    private java.lang.CharSequence device_type;
    private java.lang.CharSequence ip_address;
    private java.lang.CharSequence country_code;
    private java.lang.CharSequence city;
    private java.lang.CharSequence session_id;
    private java.lang.CharSequence ad_position;
    private boolean is_skippable;
    private int time_watched_seconds;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.adtech.avro.AdImpression.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.event_id)) {
        this.event_id = data().deepCopy(fields()[0].schema(), other.event_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.event_type)) {
        this.event_type = data().deepCopy(fields()[1].schema(), other.event_type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.user_id)) {
        this.user_id = data().deepCopy(fields()[3].schema(), other.user_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.publisher_name)) {
        this.publisher_name = data().deepCopy(fields()[4].schema(), other.publisher_name);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.advertiser_name)) {
        this.advertiser_name = data().deepCopy(fields()[5].schema(), other.advertiser_name);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[6].schema(), other.campaign_id);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.bid_price)) {
        this.bid_price = data().deepCopy(fields()[7].schema(), other.bid_price);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.device_type)) {
        this.device_type = data().deepCopy(fields()[8].schema(), other.device_type);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.ip_address)) {
        this.ip_address = data().deepCopy(fields()[9].schema(), other.ip_address);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.country_code)) {
        this.country_code = data().deepCopy(fields()[10].schema(), other.country_code);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.city)) {
        this.city = data().deepCopy(fields()[11].schema(), other.city);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.session_id)) {
        this.session_id = data().deepCopy(fields()[12].schema(), other.session_id);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.ad_position)) {
        this.ad_position = data().deepCopy(fields()[13].schema(), other.ad_position);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.is_skippable)) {
        this.is_skippable = data().deepCopy(fields()[14].schema(), other.is_skippable);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.time_watched_seconds)) {
        this.time_watched_seconds = data().deepCopy(fields()[15].schema(), other.time_watched_seconds);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
    }

    /**
     * Creates a Builder by copying an existing AdImpression instance
     * @param other The existing instance to copy.
     */
    private Builder(org.adtech.avro.AdImpression other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.event_id)) {
        this.event_id = data().deepCopy(fields()[0].schema(), other.event_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.event_type)) {
        this.event_type = data().deepCopy(fields()[1].schema(), other.event_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.user_id)) {
        this.user_id = data().deepCopy(fields()[3].schema(), other.user_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.publisher_name)) {
        this.publisher_name = data().deepCopy(fields()[4].schema(), other.publisher_name);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.advertiser_name)) {
        this.advertiser_name = data().deepCopy(fields()[5].schema(), other.advertiser_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.campaign_id)) {
        this.campaign_id = data().deepCopy(fields()[6].schema(), other.campaign_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.bid_price)) {
        this.bid_price = data().deepCopy(fields()[7].schema(), other.bid_price);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.device_type)) {
        this.device_type = data().deepCopy(fields()[8].schema(), other.device_type);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ip_address)) {
        this.ip_address = data().deepCopy(fields()[9].schema(), other.ip_address);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.country_code)) {
        this.country_code = data().deepCopy(fields()[10].schema(), other.country_code);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.city)) {
        this.city = data().deepCopy(fields()[11].schema(), other.city);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.session_id)) {
        this.session_id = data().deepCopy(fields()[12].schema(), other.session_id);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.ad_position)) {
        this.ad_position = data().deepCopy(fields()[13].schema(), other.ad_position);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.is_skippable)) {
        this.is_skippable = data().deepCopy(fields()[14].schema(), other.is_skippable);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.time_watched_seconds)) {
        this.time_watched_seconds = data().deepCopy(fields()[15].schema(), other.time_watched_seconds);
        fieldSetFlags()[15] = true;
      }
    }

    /**
      * Gets the value of the 'event_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return event_id;
    }


    /**
      * Sets the value of the 'event_id' field.
      * @param value The value of 'event_id'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.event_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'event_id' field has been set.
      * @return True if the 'event_id' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'event_id' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearEventId() {
      event_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'event_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventType() {
      return event_type;
    }


    /**
      * Sets the value of the 'event_type' field.
      * @param value The value of 'event_type'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setEventType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.event_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'event_type' field has been set.
      * @return True if the 'event_type' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'event_type' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearEventType() {
      event_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setTimestamp(long value) {
      validate(fields()[2], value);
      this.timestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.user_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'publisher_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getPublisherName() {
      return publisher_name;
    }


    /**
      * Sets the value of the 'publisher_name' field.
      * @param value The value of 'publisher_name'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setPublisherName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.publisher_name = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'publisher_name' field has been set.
      * @return True if the 'publisher_name' field has been set, false otherwise.
      */
    public boolean hasPublisherName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'publisher_name' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearPublisherName() {
      publisher_name = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'advertiser_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getAdvertiserName() {
      return advertiser_name;
    }


    /**
      * Sets the value of the 'advertiser_name' field.
      * @param value The value of 'advertiser_name'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setAdvertiserName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.advertiser_name = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'advertiser_name' field has been set.
      * @return True if the 'advertiser_name' field has been set, false otherwise.
      */
    public boolean hasAdvertiserName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'advertiser_name' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearAdvertiserName() {
      advertiser_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'campaign_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getCampaignId() {
      return campaign_id;
    }


    /**
      * Sets the value of the 'campaign_id' field.
      * @param value The value of 'campaign_id'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setCampaignId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.campaign_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'campaign_id' field has been set.
      * @return True if the 'campaign_id' field has been set, false otherwise.
      */
    public boolean hasCampaignId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'campaign_id' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearCampaignId() {
      campaign_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'bid_price' field.
      * @return The value.
      */
    public double getBidPrice() {
      return bid_price;
    }


    /**
      * Sets the value of the 'bid_price' field.
      * @param value The value of 'bid_price'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setBidPrice(double value) {
      validate(fields()[7], value);
      this.bid_price = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'bid_price' field has been set.
      * @return True if the 'bid_price' field has been set, false otherwise.
      */
    public boolean hasBidPrice() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'bid_price' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearBidPrice() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'device_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceType() {
      return device_type;
    }


    /**
      * Sets the value of the 'device_type' field.
      * @param value The value of 'device_type'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setDeviceType(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.device_type = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'device_type' field has been set.
      * @return True if the 'device_type' field has been set, false otherwise.
      */
    public boolean hasDeviceType() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'device_type' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearDeviceType() {
      device_type = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'ip_address' field.
      * @return The value.
      */
    public java.lang.CharSequence getIpAddress() {
      return ip_address;
    }


    /**
      * Sets the value of the 'ip_address' field.
      * @param value The value of 'ip_address'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setIpAddress(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.ip_address = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'ip_address' field has been set.
      * @return True if the 'ip_address' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'ip_address' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearIpAddress() {
      ip_address = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'country_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountryCode() {
      return country_code;
    }


    /**
      * Sets the value of the 'country_code' field.
      * @param value The value of 'country_code'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setCountryCode(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.country_code = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'country_code' field has been set.
      * @return True if the 'country_code' field has been set, false otherwise.
      */
    public boolean hasCountryCode() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'country_code' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearCountryCode() {
      country_code = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.city = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearCity() {
      city = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'session_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getSessionId() {
      return session_id;
    }


    /**
      * Sets the value of the 'session_id' field.
      * @param value The value of 'session_id'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setSessionId(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.session_id = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'session_id' field has been set.
      * @return True if the 'session_id' field has been set, false otherwise.
      */
    public boolean hasSessionId() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'session_id' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearSessionId() {
      session_id = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'ad_position' field.
      * @return The value.
      */
    public java.lang.CharSequence getAdPosition() {
      return ad_position;
    }


    /**
      * Sets the value of the 'ad_position' field.
      * @param value The value of 'ad_position'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setAdPosition(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.ad_position = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'ad_position' field has been set.
      * @return True if the 'ad_position' field has been set, false otherwise.
      */
    public boolean hasAdPosition() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'ad_position' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearAdPosition() {
      ad_position = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'is_skippable' field.
      * @return The value.
      */
    public boolean getIsSkippable() {
      return is_skippable;
    }


    /**
      * Sets the value of the 'is_skippable' field.
      * @param value The value of 'is_skippable'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setIsSkippable(boolean value) {
      validate(fields()[14], value);
      this.is_skippable = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'is_skippable' field has been set.
      * @return True if the 'is_skippable' field has been set, false otherwise.
      */
    public boolean hasIsSkippable() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'is_skippable' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearIsSkippable() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'time_watched_seconds' field.
      * @return The value.
      */
    public int getTimeWatchedSeconds() {
      return time_watched_seconds;
    }


    /**
      * Sets the value of the 'time_watched_seconds' field.
      * @param value The value of 'time_watched_seconds'.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder setTimeWatchedSeconds(int value) {
      validate(fields()[15], value);
      this.time_watched_seconds = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'time_watched_seconds' field has been set.
      * @return True if the 'time_watched_seconds' field has been set, false otherwise.
      */
    public boolean hasTimeWatchedSeconds() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'time_watched_seconds' field.
      * @return This builder.
      */
    public org.adtech.avro.AdImpression.Builder clearTimeWatchedSeconds() {
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AdImpression build() {
      try {
        AdImpression record = new AdImpression();
        record.event_id = fieldSetFlags()[0] ? this.event_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.event_type = fieldSetFlags()[1] ? this.event_type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.user_id = fieldSetFlags()[3] ? this.user_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.publisher_name = fieldSetFlags()[4] ? this.publisher_name : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.advertiser_name = fieldSetFlags()[5] ? this.advertiser_name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.campaign_id = fieldSetFlags()[6] ? this.campaign_id : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.bid_price = fieldSetFlags()[7] ? this.bid_price : (java.lang.Double) defaultValue(fields()[7]);
        record.device_type = fieldSetFlags()[8] ? this.device_type : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.ip_address = fieldSetFlags()[9] ? this.ip_address : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.country_code = fieldSetFlags()[10] ? this.country_code : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.city = fieldSetFlags()[11] ? this.city : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.session_id = fieldSetFlags()[12] ? this.session_id : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.ad_position = fieldSetFlags()[13] ? this.ad_position : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.is_skippable = fieldSetFlags()[14] ? this.is_skippable : (java.lang.Boolean) defaultValue(fields()[14]);
        record.time_watched_seconds = fieldSetFlags()[15] ? this.time_watched_seconds : (java.lang.Integer) defaultValue(fields()[15]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AdImpression>
    WRITER$ = (org.apache.avro.io.DatumWriter<AdImpression>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AdImpression>
    READER$ = (org.apache.avro.io.DatumReader<AdImpression>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.event_id);

    out.writeString(this.event_type);

    out.writeLong(this.timestamp);

    out.writeString(this.user_id);

    out.writeString(this.publisher_name);

    out.writeString(this.advertiser_name);

    out.writeString(this.campaign_id);

    out.writeDouble(this.bid_price);

    out.writeString(this.device_type);

    out.writeString(this.ip_address);

    out.writeString(this.country_code);

    out.writeString(this.city);

    out.writeString(this.session_id);

    out.writeString(this.ad_position);

    out.writeBoolean(this.is_skippable);

    out.writeInt(this.time_watched_seconds);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.event_id = in.readString(this.event_id instanceof Utf8 ? (Utf8)this.event_id : null);

      this.event_type = in.readString(this.event_type instanceof Utf8 ? (Utf8)this.event_type : null);

      this.timestamp = in.readLong();

      this.user_id = in.readString(this.user_id instanceof Utf8 ? (Utf8)this.user_id : null);

      this.publisher_name = in.readString(this.publisher_name instanceof Utf8 ? (Utf8)this.publisher_name : null);

      this.advertiser_name = in.readString(this.advertiser_name instanceof Utf8 ? (Utf8)this.advertiser_name : null);

      this.campaign_id = in.readString(this.campaign_id instanceof Utf8 ? (Utf8)this.campaign_id : null);

      this.bid_price = in.readDouble();

      this.device_type = in.readString(this.device_type instanceof Utf8 ? (Utf8)this.device_type : null);

      this.ip_address = in.readString(this.ip_address instanceof Utf8 ? (Utf8)this.ip_address : null);

      this.country_code = in.readString(this.country_code instanceof Utf8 ? (Utf8)this.country_code : null);

      this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);

      this.session_id = in.readString(this.session_id instanceof Utf8 ? (Utf8)this.session_id : null);

      this.ad_position = in.readString(this.ad_position instanceof Utf8 ? (Utf8)this.ad_position : null);

      this.is_skippable = in.readBoolean();

      this.time_watched_seconds = in.readInt();

    } else {
      for (int i = 0; i < 16; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.event_id = in.readString(this.event_id instanceof Utf8 ? (Utf8)this.event_id : null);
          break;

        case 1:
          this.event_type = in.readString(this.event_type instanceof Utf8 ? (Utf8)this.event_type : null);
          break;

        case 2:
          this.timestamp = in.readLong();
          break;

        case 3:
          this.user_id = in.readString(this.user_id instanceof Utf8 ? (Utf8)this.user_id : null);
          break;

        case 4:
          this.publisher_name = in.readString(this.publisher_name instanceof Utf8 ? (Utf8)this.publisher_name : null);
          break;

        case 5:
          this.advertiser_name = in.readString(this.advertiser_name instanceof Utf8 ? (Utf8)this.advertiser_name : null);
          break;

        case 6:
          this.campaign_id = in.readString(this.campaign_id instanceof Utf8 ? (Utf8)this.campaign_id : null);
          break;

        case 7:
          this.bid_price = in.readDouble();
          break;

        case 8:
          this.device_type = in.readString(this.device_type instanceof Utf8 ? (Utf8)this.device_type : null);
          break;

        case 9:
          this.ip_address = in.readString(this.ip_address instanceof Utf8 ? (Utf8)this.ip_address : null);
          break;

        case 10:
          this.country_code = in.readString(this.country_code instanceof Utf8 ? (Utf8)this.country_code : null);
          break;

        case 11:
          this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
          break;

        case 12:
          this.session_id = in.readString(this.session_id instanceof Utf8 ? (Utf8)this.session_id : null);
          break;

        case 13:
          this.ad_position = in.readString(this.ad_position instanceof Utf8 ? (Utf8)this.ad_position : null);
          break;

        case 14:
          this.is_skippable = in.readBoolean();
          break;

        case 15:
          this.time_watched_seconds = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










